MODEL:
  META_ARCHITECTURE: "SOLOv2"
  MASK_ON: True
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
DATASETS:
  TRAIN: ("jr_train",)
  TEST: ("jr_val",)
DATALOADER:
  NUM_WORKERS: 2
  FILTER_EMPTY_ANNOTATIONS: False
TEST:
  EVAL_PERIOD: 20
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0005
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 100
  STEPS: (,)
  MAX_ITER: 100
INPUT:
  MIN_SIZE_TRAIN: (480,)
  MAX_SIZE_TRAIN: 640
  MASK_FORMAT: "bitmask"
  RANDOM_FLIP: "none"
  CROP:
    ENABLED: False
VERSION: 2