_BASE_: "Base-SOLOv2.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
TEST:
  EVAL_PERIOD: 20
SOLVER:
  STEPS: (10000,)
  MAX_ITER: 7500
  BASE_LR: 0.0001
  CHECKPOINT_PERIOD: 75

